# Generated by Django 2.0 on 2017-12-14 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
