# Generated by Django 2.0 on 2017-12-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
